name: Bot Doidin

on: workflow_dispatch

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/bot-doidin:latest      
    CD:
         runs-on: ubuntu-latest
         needs: [CI]
         steps:
             - name: SSH Connect AWS
               uses: appleboy/ssh-action@v1.0.3
               with: 
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  script: |
                      echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
                      docker pull weslleywna/bot-doidin:latest
                      docker stop bot-doidin
                      docker rm bot-doidin
                      docker run -d --restart always -e "DISCORD_TOKEN=${{ vars.DISCORD_TOKEN }}" -e "CLIENT_ID=${{ vars.CLIENT_ID }}" -e "DOCKER_DEPLOY=${{ vars.DOCKER_DEPLOY }}" --name bot-doidin weslleywna/bot-doidin:latest
                      docker image prune -a -f
    
